version: 2

project_name: certin

builds:
  - binary: certin
    main: ./cmd/certin
    env:
      - CGO_ENABLED=0
    ldflags:
      # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}`.
      -s -w -X github.com/joemiller/certin/cmd/certin/commands.version={{.Version}}+{{.ShortCommit}}
    goos:
      - linux
      - darwin
      # - windows
      - freebsd
      - openbsd
      # - dragonfly
      # - netbsd
    goarch:
      - amd64
      # - arm
      - arm64
    goarm:
      - ""
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: 386

archives:
  # binary-only releases - all platforms
  - id: binaries
    formats: [binary]
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
  # archive releases containing: binary, readme, and license. tarballs (macos, linux), zip (windows)
  - id: archives
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "skip ci"
      - "ci skip"
      - Merge pull request
      - Merge branch

brews:
  - ids:
      - archives
    repository:
      owner: joemiller
      name: homebrew-taps
    commit_author:
      name: joe miller
      email: certin@joemiller.me
    directory: Formula
    homepage: "https://github.com/joemiller/certin"
    description: "Certin is a Go library and CLI for quickly creating keys and certificates for use as test fixtures."
# TODO(joem): re-enable docker builds and add a multi-arch manifest. Also switch to ghcr.io
# dockers:
#   # primary docker image for amd64 arch
#   - dockerfile: Dockerfile
#     ids:
#       - certin
#     goos: linux
#     goarch: amd64
#     image_templates:
#       - "joemiller/certin:{{ .Tag }}" # v1.0.0
#       - "joemiller/certin:v{{ .Major }}" # v1
#       - "joemiller/certin:v{{ .Major }}.{{ .Minor }}" # v1.0
#       - "joemiller/certin:latest"
#   # build a docker image for arm64 arch
#   - dockerfile: Dockerfile
#     ids:
#       - certin
#     goos: linux
#     goarch: arm64
#     goarm: ""
#     image_templates:
#       - "joemiller/certin:{{ .Tag }}-arm64" # v1.0.0
#       - "joemiller/certin:v{{ .Major }}-arm64" # v1
#       - "joemiller/certin:v{{ .Major }}.{{ .Minor }}-arm64" # v1.0
#       - "joemiller/certin:latest-arm64"
