name: main
on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: install golangci-lint
        run: |
          mkdir -p "$HOME/bin"
          # TODO: remove golangci-lint pin when release issue is fixed: https://github.com/golangci/golangci-lint/issues/1157
          curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b "$HOME/bin" v1.26.0
          echo "::add-path::$HOME/bin"
        shell: bash # force windows to use git-bash for access to curl

      - name: install goreleaser
        # only need to lint goreleaser on one platform:
        if: startsWith(runner.os, 'Linux')
        run: curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sudo sh -s -- -b /usr/local/bin

      - run: make lint
        shell: bash
      - run: make test
        shell: bash
